pipeone:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: chaitanya
      dbname: pipeone
      schema: public
      threads: 4